"use client";

import { GTBasic } from "@geavila/gt-design";

export const metadata = {
  title: "Create Next App With GT Design",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,600&family=Rubik+Bubbles&display=swap"
        rel="stylesheet"
      />

      <GTBasic>{children}</GTBasic>
    </html>
  );
}
