import { Kanit } from "next/font/google";
import { useEffect } from "react";

const kanit = Kanit({
  weight: ["100", "200", "300", "400", "500", "700", "900"],
  style: ["italic", "normal"],
  subsets: ["latin-ext"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App With GT Design",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en-US" }, { lang: "de" }];
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={params.lang} className={kanit.className}>
      <body>{children}</body>
    </html>
  );
}
