import { Kanit } from "next/font/google";
import { NextIntlClientProvider } from "next-intl/client";
import StyledComponentsRegistry from "./registry";
import { notFound } from "next/navigation";

const kanit = Kanit({
  weight: ["100", "200", "300", "400", "500", "700", "900"],
  style: ["italic", "normal"],
  subsets: ["latin-ext"],
  display: "swap",
});

export const metadata = {
  template: "%s | Acme",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en-US" }, { lang: "pt-BR" }];
}

// this page is dynamic because the cookies are used to set the theme
export const dynamic = true;

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  let messages = {};

  try {
    messages = (await import(`../../dictionaries/${params.lang}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <StyledComponentsRegistry>
      <html lang={params.lang} className={kanit.className}>
        <body>
          <NextIntlClientProvider locale={params.lang} messages={messages}>
            {children}
          </NextIntlClientProvider>
        </body>
      </html>
    </StyledComponentsRegistry>
  );
}
